USE [master]
GO
/****** Object:  Database [AdvanceWebApi]    Script Date: 15-10-2021 11:56:40 ******/
CREATE DATABASE [AdvanceWebApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdvanceWebApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AdvanceWebApi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AdvanceWebApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AdvanceWebApi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AdvanceWebApi] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdvanceWebApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AdvanceWebApi] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET ARITHABORT OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AdvanceWebApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AdvanceWebApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET  ENABLE_BROKER 
GO
ALTER DATABASE [AdvanceWebApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AdvanceWebApi] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET RECOVERY FULL 
GO
ALTER DATABASE [AdvanceWebApi] SET  MULTI_USER 
GO
ALTER DATABASE [AdvanceWebApi] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AdvanceWebApi] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AdvanceWebApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AdvanceWebApi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AdvanceWebApi] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AdvanceWebApi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'AdvanceWebApi', N'ON'
GO
ALTER DATABASE [AdvanceWebApi] SET QUERY_STORE = OFF
GO
USE [AdvanceWebApi]
GO
/****** Object:  Table [dbo].[Designation]    Script Date: 15-10-2021 11:56:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Designation](
	[DesgId] [int] IDENTITY(10,1) NOT NULL,
	[DesgName] [varchar](50) NULL,
	[DesgSalary] [numeric](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[DesgId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 15-10-2021 11:56:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[Id] [int] IDENTITY(100,2) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Department] [varchar](50) NOT NULL,
	[Gender] [char](1) NOT NULL,
	[DesignationId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD FOREIGN KEY([DesignationId])
REFERENCES [dbo].[Designation] ([DesgId])
GO
USE [master]
GO
ALTER DATABASE [AdvanceWebApi] SET  READ_WRITE 
GO
